# TencentOS 3.1 自动安装虚拟机创建脚本
# 使用 Kickstart 实现无人值守安装

param(
    [string]$VMPath = "D:\Hyper-V\VMs",
    [string]$SwitchName = "PigstyExternal",
    [int]$CPUCount = 4,
    [int]$MemoryGB = 8,
    [int]$DiskGB = 100,
    [string]$ISOPath = "d:\Models\pigsty\v4_txos\TencentOS-Server-3.1-20240925.0-TK4-x86_64-minimal.iso",
    [string]$KSPath = "d:\Models\pigsty\v4_txos\ks",
    [string]$BaseIP = "192.168.1",
    [string]$Gateway = "192.168.1.1",
    [string]$DNS = "8.8.8.8,114.114.114.114",
    [string]$RootPassword = "Pigsty@2024"
)

$ErrorActionPreference = "Stop"

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $color = switch ($Level) {
        "INFO"  { "Green" }
        "WARN"  { "Yellow" }
        "ERROR" { "Red" }
        default { "White" }
    }
    Write-Host "[$(Get-Date -Format 'HH:mm:ss')] [$Level] $Message" -ForegroundColor $color
}

# 节点配置
$nodes = @(
    @{ Name = "pigsty-node1"; IP = "$BaseIP.11"; Role = "meta" },
    @{ Name = "pigsty-node2"; IP = "$BaseIP.12"; Role = "replica" },
    @{ Name = "pigsty-node3"; IP = "$BaseIP.13"; Role = "replica" }
)

# 创建 Kickstart 配置目录
if (-not (Test-Path $KSPath)) {
    New-Item -Path $KSPath -ItemType Directory -Force | Out-Null
}

# 为每个节点生成 Kickstart 配置
foreach ($node in $nodes) {
    $ksContent = @"
# TencentOS 3.1 Kickstart for $($node.Name)
# Generated by create_pigsty_vms_auto.ps1

# 安装模式
install
text

# 键盘和语言
keyboard --vckeymap=us --xlayouts='us'
lang en_US.UTF-8

# 时区
timezone Asia/Shanghai --utc

# 网络配置 (静态IP)
network --bootproto=static --device=link --ip=$($node.IP) --netmask=255.255.255.0 --gateway=$Gateway --nameserver=$DNS --hostname=$($node.Name) --activate

# root 密码
rootpw --plaintext $RootPassword

# 创建管理员用户
user --name=admin --password=$RootPassword --plaintext --gecos="Admin User" --groups=wheel

# 启用服务
services --enabled=sshd,NetworkManager

# 防火墙和 SELinux
firewall --disabled
selinux --permissive

# 引导加载程序
bootloader --location=mbr

# 磁盘分区
autopart --type=lvm
clearpart --all --initlabel

# 软件包
%packages --nobase
@core
openssh-server
openssh-clients
sudo
vim-minimal
curl
wget
tar
gzip
net-tools
bind-utils
bash-completion
python3
%end

# 安装后脚本
%post --log=/root/ks-post.log
#!/bin/bash

# 配置 sudo 免密
echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/wheel

# 配置 SSH
sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
sed -i 's/^PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
systemctl restart sshd

# 修改 os-release 适配 Pigsty
cp /etc/os-release /etc/os-release.bak
cat > /etc/os-release << 'EOF'
NAME="TencentOS Server"
VERSION="3.1 (Compatible with EL8 for Pigsty)"
ID="rocky"
ID_LIKE="rhel centos fedora tencentos"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="TencentOS Server 3.1 (EL8 Compatible)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:rocky:rocky:8"
HOME_URL="https://tlinux.tencent.com/"
BUG_REPORT_URL="https://tlinux.tencent.com/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
EOF

# 写入节点信息
echo "NODE_NAME=$($node.Name)" >> /etc/pigsty.conf
echo "NODE_IP=$($node.IP)" >> /etc/pigsty.conf
echo "NODE_ROLE=$($node.Role)" >> /etc/pigsty.conf

echo "Kickstart completed for $($node.Name) at $(date)" >> /root/ks-post.log
%end

reboot
"@
    
    $ksFile = Join-Path $KSPath "$($node.Name).cfg"
    $ksContent | Out-File -FilePath $ksFile -Encoding ASCII
    Write-Log "生成 Kickstart: $ksFile"
}

# 创建 ISO 启动脚本
Write-Log "创建虚拟机..."

# 检查 ISO 文件
if (-not (Test-Path $ISOPath)) {
    Write-Log "ISO 文件不存在: $ISOPath" "ERROR"
    exit 1
}

# 创建虚拟机目录
if (-not (Test-Path $VMPath)) {
    New-Item -Path $VMPath -ItemType Directory -Force | Out-Null
}

# 检查虚拟交换机
$switch = Get-VMSwitch -Name $SwitchName -ErrorAction SilentlyContinue
if (-not $switch) {
    Write-Log "虚拟交换机不存在: $SwitchName" "ERROR"
    Write-Log "请先创建外部交换机:"
    Write-Log "  `$adapter = Get-NetAdapter | Where-Object { `$_.Status -eq 'Up' } | Select-Object -First 1"
    Write-Log "  New-VMSwitch -Name '$SwitchName' -NetAdapterName `$adapter.Name -AllowManagementOS `$true"
    exit 1
}

# 创建虚拟机函数
function New-PigstyVM {
    param(
        [string]$VMName,
        [string]$Path,
        [string]$SwitchName,
        [int]$CPUCount,
        [int64]$MemoryBytes,
        [int64]$DiskBytes,
        [string]$ISOPath,
        [string]$KSFile
    )
    
    Write-Log "创建虚拟机: $VMName"
    
    $vmDir = Join-Path $Path $VMName
    $vhdPath = Join-Path $vmDir "$VMName.vhdx"
    
    # 创建目录
    New-Item -Path $vmDir -ItemType Directory -Force | Out-Null
    
    # 创建虚拟硬盘
    Write-Log "  创建虚拟硬盘: $([math]::Round($DiskBytes/1GB, 0)) GB"
    New-VHD -Path $vhdPath -SizeBytes $DiskBytes -Dynamic | Out-Null
    
    # 创建虚拟机 (Generation 2)
    $vm = New-VM -Name $VMName -Path $vmDir -MemoryStartupBytes $MemoryBytes `
        -BootDevice VHD -VHDPath $vhdPath -SwitchName $SwitchName -Generation 2
    
    # 配置 CPU
    Set-VM -Name $VMName -ProcessorCount $CPUCount
    
    # 挂载 ISO
    Add-VMDvdDrive -VMName $VMName -Path $ISOPath
    
    # 启用嵌套虚拟化
    Set-VMProcessor -VMName $VMName -ExposeVirtualizationExtensions $true
    
    # 设置 DVD 启动
    $dvd = Get-VMDvdDrive -VMName $VMName
    Set-VMFirmware -VMName $VMName -FirstBootDevice $dvd
    
    Write-Log "  虚拟机创建完成"
    return $vm
}

# 创建所有虚拟机
$memoryBytes = $MemoryGB * 1GB
$diskBytes = $DiskGB * 1GB

foreach ($node in $nodes) {
    $existingVM = Get-VM -Name $node.Name -ErrorAction SilentlyContinue
    if ($existingVM) {
        Write-Log "虚拟机已存在: $($node.Name)" "WARN"
        continue
    }
    
    $ksFile = Join-Path $KSPath "$($node.Name).cfg"
    New-PigstyVM -VMName $node.Name -Path $VMPath -SwitchName $SwitchName `
        -CPUCount $CPUCount -MemoryBytes $memoryBytes -DiskBytes $diskBytes `
        -ISOPath $ISOPath -KSFile $ksFile
}

# 显示结果
Write-Log "`n============================================"
Write-Log "虚拟机创建完成!"
Write-Log "============================================"
Write-Log ""
Write-Log "虚拟机列表:"
Get-VM -Name "pigsty-node*" | Format-Table Name, State, CPUCount, MemoryStartup -AutoSize

Write-Log ""
Write-Log "网络配置:"
Write-Log "  交换机: $SwitchName"
foreach ($node in $nodes) {
    Write-Log "  $($node.Name): $($node.IP)"
}

Write-Log ""
Write-Log "Kickstart 文件位置: $KSPath"
Write-Log ""
Write-Log "============================================"
Write-Log "自动安装说明"
Write-Log "============================================"
Write-Log ""
Write-Log "由于 Hyper-V Gen2 不支持直接传递 Kickstart 参数，"
Write-Log "需要手动在启动菜单添加 ks 参数。"
Write-Log ""
Write-Log "方法 1: 手动安装 (推荐)"
Write-Log "  1. 启动虚拟机: Start-VM -Name 'pigsty-node1'"
Write-Log "  2. 在 GRUB 菜单按 'e' 编辑启动项"
Write-Log "  3. 在 linux 行末尾添加: inst.ks=http://YOUR_HTTP_SERVER/ks/pigsty-node1.cfg"
Write-Log "  4. 按 Ctrl+X 启动安装"
Write-Log ""
Write-Log "方法 2: 创建自定义 ISO"
Write-Log "  1. 解压 ISO 文件"
Write-Log "  2. 修改 isolinux/isolinux.cfg 添加 ks 参数"
Write-Log "  3. 重新打包 ISO"
Write-Log ""
Write-Log "方法 3: 使用 HTTP 服务器"
Write-Log "  1. 在宿主机启动 HTTP 服务器:"
Write-Log "     cd $KSPath"
Write-Log "     python -m http.server 8080"
Write-Log "  2. 虚拟机启动时添加 ks 参数:"
Write-Log "     inst.ks=http://HOST_IP:8080/pigsty-node1.cfg"
Write-Log ""
Write-Log "============================================"
Write-Log "快速启动命令"
Write-Log "============================================"
Write-Log "Start-VM -Name 'pigsty-node1','pigsty-node2','pigsty-node3'"
